-- MySQL Script generated by MySQL Workbench
-- Thu May 15 01:12:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_user` DEFAULT CHARACTER SET utf8 ;
USE `app_user` ;

-- -----------------------------------------------------
-- Table `app_user`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_user`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,  -- 添加 AUTO_INCREMENT
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_type` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `app_user`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_user`.`subject` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,  -- 添加 AUTO_INCREMENT
  `subject_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `app_user`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_user`.`question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,  -- 添加 AUTO_INCREMENT
  `question_text` TEXT(1000) NOT NULL,
  `question_type` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `standard_answer` TEXT(500) NULL,
  PRIMARY KEY (`question_id`),
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `app_user`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `app_user`.`options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_user`.`options` (
  `option_id` INT NOT NULL AUTO_INCREMENT,  -- 添加 AUTO_INCREMENT
  `question_id` INT NOT NULL,
  `option_text` VARCHAR(45) NULL,
  `is_correct` TINYINT NULL,
  PRIMARY KEY (`option_id`),
  INDEX `quesion_id_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `quesion_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `app_user`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `app_user`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_user`.`answer` (
  `anwser_id` INT NOT NULL AUTO_INCREMENT,  -- 添加 AUTO_INCREMENT
  `user_id` INT NULL,
  `is_correct` TINYINT NULL,
  PRIMARY KEY (`anwser_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `app_user`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `app_user`.`WrongQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_user`.`WrongQuestion` (
  `WQ_id` INT NOT NULL AUTO_INCREMENT,  -- 添加 AUTO_INCREMENT
  `user_id` INT NOT NULL,
  `question_id` INT NULL,
  PRIMARY KEY (`WQ_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `question_id_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `app_user`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `app_user`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `app_user`.`user_answer_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_user`.`user_answer_options` (
  `iduser_answer_options` INT NOT NULL AUTO_INCREMENT,  -- 添加 AUTO_INCREMENT
  `option_id` INT NULL,
  `answer_id` INT NULL,
  PRIMARY KEY (`iduser_answer_options`),
  INDEX `option_id_idx` (`option_id` ASC) VISIBLE,
  INDEX `answer_id_idx` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `option_id`
    FOREIGN KEY (`option_id`)
    REFERENCES `app_user`.`options` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `app_user`.`answer` (`anwser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;